site_name:        EzXML.jl
repo_url:         https://github.com/bicycle1885/EzXML.jl
site_description: XML/HTML tools for primates
site_author:      bicycle1885

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code

docs_dir: 'build'

pages:
  - Manual: manual.md
  - References: references.md
  - Developer Notes: devnotes.md
